/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-09-26 11:53:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.*;

public final class givereview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
ResultSet resultset =null;
      out.write('\r');
      out.write('\n');
ResultSet resultset1 =null;
      out.write('\r');
      out.write('\n');
ResultSet resultset2 =null;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\r\n");
      out.write("\r\n");
      out.write("<title>Book Review System</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/960_24_col.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/fonts.css\"\r\n");
      out.write("\tcharset=\"utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/prettyPhoto.css\" />\r\n");
      out.write("<link href=\"css/jquery-ui-1.9.1.date-picker.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link href=\"css/validationEngine.jquery.css\" rel=\"stylesheet\"\r\n");
      out.write("\ttype=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/forms.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar relTag = \"login\";\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<style>\r\n");
      out.write("span.msg {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction validateReviewField()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t     \t   var msg = document.getElementById(\"addreview\").value;\r\n");
      out.write("\t     \t  document.getElementById(\"errmsg\").style.color = \"red\";\r\n");
      out.write("\t     \t  \r\n");
      out.write("\t     \t   if(!isNaN(msg))\r\n");
      out.write("\t     \t   {\r\n");
      out.write("\t    \t\t   document.getElementById(\"errmsg\").innerHTML = \"Only characters allow\";\r\n");
      out.write("\t    \t\t   document.getElementById(\"addreview\").value=\"\";\r\n");
      out.write("\t    \t   }\r\n");
      out.write("\t     \t   else if(msg.length<5)\r\n");
      out.write("\t     \t   {\r\n");
      out.write("\t   \t\t   \t\tdocument.getElementById(\"errmsg\").innerHTML = \"review is too short\";\r\n");
      out.write("\t   \t\t   \tdocument.getElementById(\"addreview\").value=\"\";\r\n");
      out.write("\t   \t   \t\t}\r\n");
      out.write("\t     \t   else if(msg.length>200)\r\n");
      out.write("\t     \t   {\r\n");
      out.write("\t  \t\t   \t\tdocument.getElementById(\"errmsg\").innerHTML = \"review is too large\";\r\n");
      out.write("\t  \t\t   \tdocument.getElementById(\"addreview\").value=\"\";\r\n");
      out.write("\t  \t   \t\t}\r\n");
      out.write("\t     \t   else\r\n");
      out.write("\t     \t\t   {\r\n");
      out.write("\t     \t\t  document.getElementById(\"errmsg\").innerHTML = \"\";\r\n");
      out.write("\t     \t\t   }\r\n");
      out.write("\t     \t   \r\n");
      out.write("\t        }  \r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- HEADER START -->\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"dark-nav\">\r\n");
      out.write("\t\t\t<div class=\"container_24\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav-alt\">\r\n");
      out.write("\t\t\t\t\t\t");
  int id=(Integer)session.getAttribute("userid");
								//int bid=Integer.parseInt(request.getParameter("bookid"));
								String bid=request.getParameter("bookid");
								session.setAttribute("userid",id);
								session.setAttribute("bookid",bid);  
								String username;
						
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
	
							try{  
								
				  
								Connection con=Connect.getConnection();
								Statement stmt=Connect.getStatement();
								ResultSet rs=stmt.executeQuery("select * from user where userid='"+id+"'");  
				  
								while(rs.next())
								{
									username =rs.getString(2);
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<b> Welcome:");
 out.println(username); 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</b>\r\n");
      out.write("\t\t\t\t\t\t");

								
								}
				
				  		
				  
					}catch(Exception e){ System.out.println(e);}  
				  
			
 						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"grid_12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav-alt\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"#\" class=\"float-right\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"logout.jsp\"><B>User Logout</B></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"container_24\">\r\n");
      out.write("\t\t\t<div class=\"grid_4\">\r\n");
      out.write("\t\t\t\t<img alt=\"logo\" src=\"images/bookreview.png\" class=\"img-logo\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"grid_20\">\r\n");
      out.write("\t\t\t\t<h1 class=\"title\">Book Review System</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"nav-main-container\">\r\n");
      out.write("\t\t\t<div class=\"container_24\">\r\n");
      out.write("\t\t\t\t<div class=\"grid_24\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- HEADER END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- CONTENTS START -->\r\n");
      out.write("\t<div class=\"container_24\">\r\n");
      out.write("\t\t<div class=\"grid_24\">\r\n");
      out.write("\t\t\t<div class=\"contents\">\r\n");
      out.write("\t\t\t\t<div class=\"padding_20\">\r\n");
      out.write("\t\t\t\t\t<h2>Review</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"grid_6 alpha\">\r\n");
      out.write("\t\t\t\t\t<div class=\"padding_20\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"accordion nav-sidebar\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Book</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"UserIndex.jsp\">All Books </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"searchbook.jsp\">Search </a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<h3>Account</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"changeuserpassword.jsp\">Change Password</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"grid_18 omega\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"padding_20 text-justify\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tabs-container\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#tabs-1\">All Review</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#tabs-2\">Give Review</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#tabs-3\">History</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tabs-contents\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"tabs-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"frmMain\" action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"form-table\" style=\"width: auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

									 
    									try{
    											
    										Connection con=Connect.getConnection();
    										Statement stmt=Connect.getStatement();
    										
											resultset1 =stmt.executeQuery("select user.username,booktable.title,reviewtable.reviews from user,booktable,reviewtable where user.userid=reviewtable.userid and booktable.bookid=reviewtable.bookid ");


											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table border='0' width='100%' class='table11'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Book Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>User Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Review</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												while(resultset1.next())
												{
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(2) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(1));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(3));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													
												}
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

       										 
       										
    											}
        													catch(Exception e)
        												{
             												out.println("wrong entry"+e);
        												}
										
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"tabs-2\" style=\"overflow: auto; max-height: 450px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"frmMain2\" class=\"frmMain\" action=\"ReviewServlet\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmethod=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"form-table\" style=\"width: auto\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table border='0' width='100%' class='table11'>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

    									try{
    									
    										Connection con=Connect.getConnection();
    										Statement stmt=Connect.getStatement();
    										ResultSet rs=stmt.executeQuery("select * from booktable where bookid='"+bid+"'");  
    						  
    										while(rs.next())
    										{
												
       										
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Book Name</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( rs.getString(2) );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Author</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( rs.getString(7));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Publication</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( rs.getString(4));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Edition</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( rs.getString(5));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>Your Review</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><textarea id=\"addreview\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"validate[required]  class=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalidate[maxSize[200]]\" style=\"width: 99%\" cols=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\trows=\"3\" name=\"addreview\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Maximum 200 Characters\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"validateReviewField()\"></textarea> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"errmsg\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>&nbsp;</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><input id=\"Submit1\" type=\"submit\" value=\"submit\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Reset1\" type=\"reset\" value=\"Reset\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonclick=\"this.form.clear();\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

       										 
       										
    											}
        													catch(Exception e)
        												{
             												out.println("wrong entry"+e);
        												}
										
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"tabs-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"frmMain4\" class=\"frmMain\" action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table class=\"form-table\" style=\"width: auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

									 int reviewid;
    									try{
    											
    										Connection con=Connect.getConnection();
    										Statement stmt=Connect.getStatement();
    										
											resultset1 =stmt.executeQuery("select reviewtable.reviewid,reviewtable.reviews,booktable.title from booktable,reviewtable where reviewtable.userid='"+id+"' and booktable.bookid=reviewtable.bookid ");


											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table border='0' width='100%' class='table11'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Review Id</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Book Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Review</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Modify</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Delete</th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												while(resultset1.next())
												{
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getInt(1) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(3) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(2));
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
 
														reviewid= resultset1.getInt(1);
														
														
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref='modifyreview.jsp?reviewid=+");
      out.print( reviewid );
      out.write("+'>Modify</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\thref='deletereview.jsp?reviewid=+");
      out.print( reviewid );
      out.write("+'>Delete</a></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												
													
												}
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

       										 
       										
    											}
        													catch(Exception e)
        												{
             												out.println("wrong entry"+e);
        												}
										
											
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- CONTENTS END -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- FOOTER START -->\r\n");
      out.write("\t<div class=\"dark-nav footer\">\r\n");
      out.write("\t\t<div class=\"container_24\">\r\n");
      out.write("\t\t\t<div class=\"grid_8\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav-alt\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"help.html\">Help</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"grid_8\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">Copyright &copy; All Rights Reserved</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"grid_8\">\r\n");
      out.write("\t\t\t\t<div class=\"text-right\">Designed &amp; Developed by Dipak</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- FOOTER START -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/jquery.validationEngine-en.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.bxslider.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /givereview.jsp(74,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.userid }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t");
        if (true) {
          _jspx_page_context.forward("userlogin.jsp");
          return true;
        }
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
