/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-09-22 09:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.*;

public final class searchbook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("\n");
ResultSet resultset =null;
      out.write('\n');
ResultSet resultset1 =null;
      out.write('\n');
ResultSet resultset2 =null;
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\n");
      out.write("\t\t\n");
      out.write("\t\t<title>Book Review System </title>\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/960_24_col.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/fonts.css\" charset=\"utf-8\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/prettyPhoto.css\" />\n");
      out.write("\t\t<link href=\"css/jquery-ui-1.9.1.date-picker.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"css/validationEngine.jquery.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/forms.css\" />\n");
      out.write("\t\t\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery-1.8.3.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tvar relTag = \"login\";\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<style>\n");
      out.write("\t\tspan.msg{\n");
      out.write("\t\tcolor:red;\n");
      out.write("\t\t}\n");
      out.write("\t\t</style>\n");
      out.write("\t\t\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("                    \n");
      out.write("\t\t\t\n");
      out.write("\t\t</script>\n");
      out.write("\t</head>\n");
      out.write("\n");
      out.write("\t<body>\n");
      out.write("\t\t<!-- HEADER START -->\n");
      out.write("\t\t<div class=\"header\">\n");
      out.write("\t\t\t<div class=\"dark-nav\">\n");
      out.write("\t\t\t\t<div class=\"container_24\">\n");
      out.write("\t\t\t\t\t<div class=\"grid_12\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav-alt\">\n");
      out.write("\t\t\t\t\t\t\t");
  int id=(Integer)session.getAttribute("userid");
								String username;
						
								
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
	
							try{  
								
				  
								Connection con=Connect.getConnection();
								Statement stmt=Connect.getStatement();
								ResultSet rs=stmt.executeQuery("select * from user where userid='"+id+"'");  
				  
								while(rs.next())
								{
									username =rs.getString(2);
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<b>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tWelcome:");
 out.println(username); 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</b>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

								
								}
				
				  		
				  
					}catch(Exception e){ System.out.println(e);}  
				  
			
 						
      out.write("\t\t\n");
      out.write(" \t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"grid_12\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav-alt\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"#\" class=\"float-right\" method=\"post\">\n");
      out.write("\t\t\t\t   \t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t     \t\t\t<li><a href=\"logout.jsp\"><B>User Logout</B></a></li>\n");
      out.write("\t\t\t\t\t\t\t     \t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"container_24\">\n");
      out.write("\t\t\t\t<div class=\"grid_4\">\n");
      out.write("\t\t\t\t\t<img alt=\"logo\" src=\"images/bookreview.png\" class=\"img-logo\" />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"grid_20\">\n");
      out.write("\t\t\t\t\t<h1 class=\"title\">Book Review System</h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"nav-main-container\">\n");
      out.write("\t\t\t\t<div class=\"container_24\">\n");
      out.write("\t\t\t\t\t<div class=\"grid_24\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- HEADER END -->\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t<!-- CONTENTS START -->\n");
      out.write("\t<div class=\"container_24\">\n");
      out.write("\t\t\t<div class=\"grid_24\">\n");
      out.write("\t\t\t\t<div class=\"contents\">\n");
      out.write("\t\t\t\t\t<div class=\"padding_20\">\n");
      out.write("\t\t\t\t\t\t<h2> Search</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"grid_6 alpha\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"padding_20\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"accordion nav-sidebar\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Book</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"UserIndex.jsp\">All Books &nbsp;[<b><span class=\"msg\"></span></b>]</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"searchbook.jsp\">Search </a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Account</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"userprofile.jsp\">User Profile</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"userchangepassword.jsp\">Change Password</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"grid_18 omega\">\n");
      out.write("\t\t\t\t\t\t \n");
      out.write("\t\t\t\t\t\t\t<div class=\"padding_20 text-justify\">\n");
      out.write("\t\t\t\t\t\t\t\t<form id=\"frmMain\"  class=\"frmMain\" action=\"#\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"form-table\" style=\"width:auto\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

									 
    									try{
    											
    										Connection con=Connect.getConnection();
    										Statement stmt=Connect.getStatement();

       											
       											
       										
											
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tSelect By\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"selectopt\" class='validate[required]' style=\"width:120%\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value= \"\">----------Select----------</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t    <option value=\"booktitle\">Book Title</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t     <option value=\"bookauthor\">Author</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t           \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t       \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"validate[required]\" name=\"title\" style=\"width:120%\" value=\"\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t&nbsp;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input id= \"Submit1\" type=\"submit\" value=\"Submit\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"Reset1\" type=\"reset\" value=\"Reset\" onclick=\"this.form.clear();\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

											if(request.getMethod()=="POST")
											{
												int bookid=0;
												//int w=Integer.parseInt(request.getParameter("ward"));
											String option=request.getParameter("selectopt");
											String title=request.getParameter("title");
											
											if(option.equals("booktitle"))
											{
												resultset1 =stmt.executeQuery("select * from booktable where title = '"+title+"' ") ;
												
											}
											else if(option.equals("bookauthor"))
											{
												resultset1 =stmt.executeQuery("select * from booktable where author = '"+title+"' ") ;
												
											}
											
											
											if(resultset1!=null)
											{
												
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<table border='0' width='100%' class='table11'>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Book Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Author</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Pages</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Publication</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Edition</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Genre</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th>Review</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 while(resultset1.next()){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(2) );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(7));
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getInt(3));
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(4));
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(	resultset1.getInt(5) );
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
      out.print( resultset1.getString(6));
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 
														 bookid= resultset1.getInt(1);
														
														
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href='givereview.jsp?bookid=+");
      out.print( bookid );
      out.write("+'>Review</a></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t    \t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t           \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t            \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        \t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t     </table>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
} 
											else
											{
												
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<script type='text/javascript'>alert('Records Not Found')</script>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

       										 
       											}
    									}
        													catch(Exception e)
        												{
             												out.println("wrong entry"+e);
        												}
										
											
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t\t</form>\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"clear\"> </div>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t<!-- CONTENTS END -->\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- FOOTER START -->\n");
      out.write("\t\t<div class=\"dark-nav footer\">\n");
      out.write("\t\t\t<div class=\"container_24\">\n");
      out.write("\t\t\t\t<div class=\"grid_8\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav-alt\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t <li><a href=\"help.html\">Help</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"grid_8\">\n");
      out.write("\t\t\t\t\t\t<div class=\"text-center\">Copyright &copy; All Rights Reserved</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"grid_8\">\n");
      out.write("\t\t\t\t\t\t<div class=\"text-right\">Designed &amp; Developed by Dipak</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t<!-- FOOTER START -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("\t\t<script src=\"js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t<script src=\"js/jquery.validationEngine.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t<script src=\"js/jquery.validationEngine-en.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery.bxslider.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/jquery.prettyPhoto.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/custom.js\"></script>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
